---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[tutorial-workstation::default]
    attributes:
