name 'tutorial-workstation'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures tutorial-workstation'
long_description 'Installs/Configures tutorial-workstation'
version '0.1.0'

depends 'chocolatey'
depends 'chrome'
